export const perkData: {[key: string]: [string, string]} = {
	"kfgame.kfperk_berserker": ["Berserker", "https://wiki.killingfloor2.com/images/thumb/d/d3/KF2_Perk_Berserker_White.png/128px-KF2_Perk_Berserker_White.png"],
	"kfgame.kfperk_commando": ["Commando", "https://wiki.killingfloor2.com/images/thumb/4/4c/KF2_Perk_Commando_White.png/128px-KF2_Perk_Commando_White.png"],
	"kfgame.kfperk_support": ["Support", "https://wiki.killingfloor2.com/images/thumb/5/53/KF2_Perk_Support_White.png/128px-KF2_Perk_Support_White.png"],
	"kfgame.kfperk_fieldmedic": ["Field Medic", "https://wiki.killingfloor2.com/images/thumb/f/f6/KF2_Perk_FieldMedic_White.png/128px-KF2_Perk_FieldMedic_White.png"],
	"kfgame.kfperk_demolitionist": ["Demolitionist", "https://wiki.killingfloor2.com/images/thumb/c/c5/KF2_Perk_Demolitionist_White.png/128px-KF2_Perk_Demolitionist_White.png"],
	"kfgame.kfperk_firebug": ["Firebug", "https://wiki.killingfloor2.com/images/thumb/c/cd/KF2_Perk_Firebug_White.png/128px-KF2_Perk_Firebug_White.png"],
	"kfgame.kfperk_gunslinger": ["Gunslinger", "https://wiki.killingfloor2.com/images/thumb/1/1f/KF2_Perk_Gunslinger_White.png/128px-KF2_Perk_Gunslinger_White.png"],
	"kfgame.kfperk_sharpshooter": ["Sharpshooter", "https://wiki.killingfloor2.com/images/thumb/2/29/KF2_Perk_Sharpshooter_White.png/128px-KF2_Perk_Sharpshooter_White.png"],
	"kfgame.kfperk_survivalist": ["Survivalist", "https://wiki.killingfloor2.com/images/thumb/e/eb/KF2_Perk_Survivalist_White.png/128px-KF2_Perk_Survivalist_White.png"],
	"kfgame.kfperk_swat": ["SWAT", "https://wiki.killingfloor2.com/images/thumb/9/9b/KF2_Perk_SWAT_White.png/128px-KF2_Perk_SWAT_White.png"],
}

export const weaponData: {[key: string]: [string, string]} = {
	"9mm": ["9mm Pistol", ""],
	"9mmDual": ["Dual 9mm Pistols", ""],
	"AA12": ["AA-12 Auto Shotgun", ""],
	"AbominationAxe": ["Battle Axe", ""],
	"AF2011": ["AF2011-A1", ""],
	"AF2011Dual": ["Dual AF2011-A1", ""],
	"Ak12": ["Kalashinikov AK-12", ""],
	"AR15": ["AR-15 Varmint Rifle", ""],
	"AutoTurret": ["Sentinel", ""],
	"AutoTurretWeapon": ["Sentinel", ""],
	"BladedPistol": ["Piranha Pistol", ""],
	"Blunderbuss": ["Blunderbuss", ""],
	"Bullpup": ["SA80 L85A2 Bullpup", ""],
	"C4": ["C4 Explosives", ""],
	"CaulkBurn": ["Caulk n' Burn", ""],
	"CenterfireMB464": ["SPX 464 Centerfire", ""],
	"ChainBat": ["Road Redeemer", ""],
	"ChiappaRhino": ["Rhino", ""],
	"ChiappaRhinoDual": ["Dual Rhino", ""],
	"Colt1911": ["M1911 Pistol", ""],
	"Colt1911Dual": ["Dual M1911 Pistols", ""],
	"CompoundBow": ["Compound Bow", ""],
	"Crossbow": ["Crossbow", ""],
	"Crovel": ["Crovel Survival Tool", ""],
	"Deagle": [".50 Desert Eagle", ""],
	"DeagleDual": ["Dual .50 Desert Eagles", ""],
	"Doshinegun": ["Doshinegun", ""],
	"DoubleBarrel": ["Double-barreled Boomstick", ""],
	"DragonsBreath": ["Dragonsbreath", ""],
	"DualBladed": ["Dual Piranha Pistols", ""],
	"ElephantGun": ["Doomstick", ""],
	"Eviscerator": ["Eviscerator", ""],
	"FAMAS": ["FAMAS Masterkey", ""],
	"FireAxe": ["Fire Axe", ""],
	"FlameThrower": ["Flamethrower", ""],
	"FlareGun": ["Spitfire", ""],
	"FlareGunDual": ["Dual Spitfires", ""],
	"FreezeThrower": ["Freezethrower", ""],
	"FNFal": ["FN FAL ACOG", ""],
	"G18": ["Riot Shield & Glock 18", ""],
	"G36C": ["G36C Assault Rifle", ""],
	"GravityImploder": ["Gravity Imploder", ""],
	"Grenade_Berserker": ["EMP Grenade", ""],
	"Grenade_Commando": ["HE Grenade", ""],
	"Grenade_Demo": ["1/2 Stick of Dynamite", ""],
	"Greande_Firebug": ["Molotov Cocktail", ""],
	"Grenade_Gunslinger": ["Nail Bomb", ""],
	"Grenade_Medic": ["Healing Grenade", ""],
	"Grenade_Sharpshooter": ["Freeze Grenade", ""],
	"Grenade_Support": ["Frag Grenade", ""],
	"Grenade_SWAT": ["FlashBang", ""],
	"Healer": ["Healer Syringe", ""],
	"Healthrower_HRG": ["HRG Healthrower", ""],
	"Hemogoblin": ["Hemogoblin", ""],
	"HK_UMP": ["Hechler & Koch UMP", ""],
	"HRG_93R": ["HRG 93R Pistol", ""],
	"HRG_93R_Dual": ["Dual HRG 93R Pistols", ""],
	"HRG_BallisticBouncer": ["HRG Ballistic Bouncer", ""],
	"HRG_BarrierRifle": ["HRG Bastion", ""],
	"HRG_BlastBrawlers": ["HRG Blast Brawlers", ""],
	"HRG_Boomy": ["HRG Tommy Boom", ""],
	"HRG_CranialPopper": ["HRG Head Hunter", ""],
	"HRG_Crossboom": ["HRG Crossboom", ""],
	"HRG_Dragonbreath": ["HRG Dragon Blaze", ""],
	"HRG_EMP_ArcGenerator": ["HRG Arc Generator", ""],
	"HRG_Energy": ["HRG Disrupter", ""],
	"HRG_Kaboomstick": ["HRG Kaboomstick", ""],
	"HRG_Locust": ["HRG Locust", ""],
	"HRG_MedicMissile": ["HRG Medic Missile", ""],
	"HRG_SonicGun": ["HRG Beluga Beat", ""],
	"HRG_Stunner": ["HRG Stunner", ""],
	"HRG_Vampire": ["HRG Vampire", ""],
	"HRG_Warthog": ["HRG Bombardier", ""],
	"HRG_WarthogWeapon": ["HRG Bombardier", ""],
	"HRGIncendiaryRifle": ["HRG Incendiary Rifle", ""],
	"HRGIncision": ["HRG Incision", ""],
	"HRGScorcher": ["HRG Scorcher", ""],
	"HRGTeslauncher": ["HRG Teslauncher", ""],
	"HRGWinterbite": ["HRG Winterbite", ""],
	"HRGWinterbiteDual": ["Dual HRG Winterbites", ""],
	"HuskCannon": ["Husk Cannon", ""],
	"HVStormCannon": ["HV Storm Cannon", ""],
	"HX25": ["HX25 Grenade Pistol", ""],
	"HZ12": ["HZ12 Multi-Action", ""],
	"IonThruster": ["Ion Thruster", ""],
	"Katana": ["Katana", ""],
	"Knife_Base": ["Knife", ""],
	"Kriss": ["Kriss SMG", ""],
	"LazerCutter": ["Killerwatt", ""],
	"M4": ["M4 Combat Shotgun", ""],
	"M14EBR": ["M14 EBR", ""],
	"M16M203": ["M16 M203 Assault Rifle", ""],
	"M32": ["M32 Grenade Launcher", ""],
	"M79": ["M79 Grenade Launcher", ""],
	"M99": ["M99 AMR", ""],
	"Mac10": ["Mac10", ""],
	"MaceAndShield": ["Bone Crusher", ""],
	"MB500": ["SG 500 Pump-Action", ""],
	"MedicBat": ["Hemoclobber", ""],
	"MedicPistol": ["HMTech-101 Pistol", ""],
	"MedicRifle": ["HMTech-401 Assault Rifle", ""],
	"MedicRifleGrenadeLauncher": ["HMTech-501 Grenade Rifle", ""],
	"MedicShotgun": ["HMTech-301 Shotgun", ""],
	"MedicSMG": ["HMTech-201 SMG", ""],
	"MG3": ["MG3 Shredder", ""],
	"MicrowaveGun": ["Microwave Gun", ""],
	"MicrowaveRifle": ["Helios Rifle", ""],
	"Mine_Reconstructor": ["Mine Reconstructor", ""],
	"Minigun": ["Minigun", ""],
	"MKB42": ["Mkb.42(H) Assault Rifle", ""],
	"MosinNagant": ["Mosin Nagant", ""],
	"MP5RAS": ["MP5RAS SMG", ""],
	"MP7": ["MP7 SMG", ""],
	"NailGun": ["VLAD-1000 Nailgun", ""],
	"NailGun_HRG": ["HRG Nailgun", ""],
	"P90": ["P90 SMG", ""],
	"ParasiteImplanter": ["Corrupter Carbine", ""],
	"Pistol_DualG18": ["Dual Glock 18C", ""],
	"Pistol_G18C": ["Glock 18C", ""],
	"PowerGloves": ["Static Strikers", ""],
	"Pulverizer": ["Pulverizer", ""],
	"RailGun": ["Rail Gun", ""],
	"Remington1858": ["Remington 1858 Revolver", ""],
	"Remington1858Dual": ["Dual Remington 1858 Revolvers", ""],
	"Rifle_FrostShotgunAxe": ["Frost Fang", ""],
	"RPG7": ["RPG-7", ""],
	"SCAR": ["SCAR-H Assault Rifle", ""],
	"Scythe": ["Blood Sickle", ""],
	"SealSqueal": ["Seal Squeal", ""],
	"Seeker6": ["Seeker Six", ""],
	"Shotgun_S12": ["S12 Shockgun",	""],
	"ShrinkRayGun": ["Reducto Ray", ""],
	"Stoner63A": ["Stoner 63A LMG", ""],
	"SW500": [".500 Magnum Revolver", ""],
	"SW500_HRG": ["HRG Backshot", ""],
	"SW500Dual": ["Dual .500 Magnum Revolvers", ""],
	"SW500Dual_HRG": ["Dual HRG Backshots", ""],
	"ThermiteBore": ["Thermite Bore", ""],
	"Thompson": ["Tommy Gun", ""],
	"Welder": ["Welder", ""],
	"Winchester1894": ["Winchester 1894", ""],
	"ZedMKIII": ["Z.E.D. MKIII", ""],
	"Zweihander": ["Zweihander", ""],
}

export interface ClassNameResolver {
	name: string;
	image: string;
}

export const resolveWeaponData = (className: string): ClassNameResolver => {
	const parsed = className.split(".");
	if(parsed.length < 2){
		return {
			name: "Unknown",
			image: "",
		};
	}

	const data = weaponData[parsed[1].split("Def_")[1]];
	return {
		name: data ? data[0] + (!parsed[0] && parsed[0] !== "KFGame" ? ` (${parsed[0]})` : "") : `Unknown (${parsed[1]})`,
		image: data ? data[1] : "",
	}
}
